### ISSUE TITLE
Couldn't resolve resource @id/default_state

### ISSUE THREAD

**Issue by mbaldinazzo** [yavski/fab-speed-dial#11]
I have this error when I try to add the fab into a coordinator layout, how can I do?

**Comment by PalakSDarji** [comment]
Found something?

**Comment by mbaldinazzo** [comment]
I solved (only for now I think) updating android studio

**Comment by d-lord** [comment]
I'm experiencing this with Android Studio 2.0, and another user posted [here](http://stackoverflow.com/q/36566622/2209946) (not much detail). The activity is fine on an emulated or physical device, it's just the preview that gets confused.

**Comment by yavski** [comment]
Sorry for the lack of feedback, I'll look into the issue at the weekend.

**Comment by mbaldinazzo** [comment]
Thanks, probably there are some problems with the CoordinatorLayout.

**Comment by mbaldinazzo** [comment]
@yavski Another question, I'd like to set the alpha when menu is open like [this](http://www.androidpolice.com/wp-content/uploads/2015/03/img_550f41a7c965a-329x585.png), how can I do? At the moment I change the visibility of a view with gray background when user clicks on the fab but I'd like to ask you if I can use any standard method. Thanks in advance.

**Comment by yavski** [comment]
@mbaldinazzo do you mean set `alpha` on the background underneath? If yes, there isn't a nice way of doing it at the moment. It would only work if the container of FabSpeedDial is a `FrameLayout`, or a subclass of it. Then you can do something like `ViewCompat.setAlpha((View) fabSpeedDial.getParent(), alpha)`. Raise another issue for it and I'll try to squeeze in support for it at library level at the weekend.
