### ISSUE TITLE
Is it possible to close the FabMenuItems with code?

### ISSUE THREAD

**Issue by Zarathes** [yavski/fab-speed-dial#14]
I need to close the FabMenu before I start a fragment transition because it messes with the collapse animation I have.

Is there anyway to do this already? Or could you make a method that I can call after finding the FabSpeedDial by id?

**Comment by yavski** [comment]
@Zarathes Update to 1.0.4 and you will have [show()](https://github.com/yavski/fab-speed-dial/blob/master/library/src/main/java/io/github/yavski/fabspeeddial/FabSpeedDial.java#L373) and [hide()](https://github.com/yavski/fab-speed-dial/blob/master/library/src/main/java/io/github/yavski/fabspeeddial/FabSpeedDial.java#L379) methods.
