### ISSUE TITLE
fab still triggers onMenuItemSelected events after calling hide()

### ISSUE THREAD

**Issue by Zarathes** [yavski/fab-speed-dial#16]
This can be/is already fixed on my side but it might be nice to actually handle in the show/hide functions you just added. 

But like the title says, the fab still opens and onMenuItemSelected still gets called even if the hide method is used.

**Comment by dstd** [comment]
@Zarathes I can't reproduce receiving `onMenuItemSelected` events after `hide` is called. Both for Sample app and my own project. Probably you need to be more specific. Also feel free to set a breakpoint on a call to `hide` and check what's going on.

**Comment by Zarathes** [comment]
Hmm, looks like you are right. Did a full reinstall of my app to be sure the update from v1.0.3 to v.1.0.4 were implemented and I can't reproduce the issue either. 

Must be Android Studio being funky again.
