### ISSUE TITLE
Crash when using id "fab"

### ISSUE THREAD

**Issue by i11072** [yavski/fab-speed-dial#18]
When using the attribute `android:id="@+id/fab"` on a FabSpeedDial element, the app won't compile:

> java.lang.ClassCastException: io.github.yavski.fabspeeddial.FabSpeedDial cannot be cast to android.support.design.widget.FloatingActionButton
> at io.github.yavski.fabspeeddial.FabSpeedDial.onAttachedToWindow(FabSpeedDial.java:239)

At least this should be mentioned somewhere.

**Comment by SvyatoslavLynda** [comment]
Hello,
You should use next code:
`FabSpeedDial fab = (FabSpeedDial) findViewById(R.id.fab);`
because FabSpeedDial and FloatingActionButton different view types

**Comment by VizGhar** [comment]
Wrong
In FabSpeedDial class is this piece of code
```
// Set up the client's FAB
fab = (FloatingActionButton) findViewById(R.id.fab);
```
Means if i use `(FabSpeedDial) findViewById(R.id.fab)` I'll get this exception. Since It will try to Cast `FloatingActionButton` (defined by lib) into `FabSpeedDial` (defined by me)

Solution is just to use other id
