### ISSUE TITLE
How make different BackgroundTint for mini fab of menu items

### ISSUE THREAD

**Issue by SvyatoslavLynda** [yavski/fab-speed-dial#20]
I need method for get Child MiniFab Items for set their backgroundTint, It's possible make this methods in new version?

**Comment by bottle-rocket-11** [comment]
This would be nice, anyone find a way to do this yet?

**Comment by fjbatresv** [comment]
Theorical this is possible if you read the doc... 

On the XML add this:

app:miniFabBackgroundTint="@android:color/white"
        app:miniFabDrawableTint="?attr/colorPrimaryDark"

**Comment by yavski** [comment]
@SvyatoslavLynda, sorry for taking ages to respond. You can achieve that by using `app:miniFabBackgroundTint` to tint the background of all mini fabs as a group, or in v.1.0.5 you'll be able to use `app:miniFabBackgroundTintList` to specify individual colors for each of your mini fabs.
