### ISSUE TITLE
Prefix custom attributes

### ISSUE THREAD

**Issue by MarcinOrlowski** [yavski/fab-speed-dial#21]
Id' recommend prefixing all custom attributes with i.e. `fsd_` or anything like that to avoid potential clash with other libraries in the project.

**Comment by yavski** [comment]
Thanks for the tip, for the sake of not breaking backwards compatibility I'll keep the existing attributes.

**Comment by MarcinOrlowski** [comment]
> Thanks for the tip, for the sake of not breaking backwards compatibility

And what's wrong with non-backward compatible changes? Just document the change clearly, and properly bump  the version

**Comment by yavski** [comment]
@MarcinOrlowski It hasn't been brought up before, it doesn't seem to be an issue that other people are facing hence the cost doesn't seem to be justified. Are you having that issue yourself? With which library is the clash? 
I'm considering doing a 1.1 where you can provide the menu items either statically via the menu resource (as it is at the minute), or dynamically via an adapter. Perhaps I can introduce that change then.
