### ISSUE TITLE
Detect main fab press

### ISSUE THREAD

**Issue by bestak** [yavski/fab-speed-dial#26]
Hello, I just want to ask, if there is a way how to detect main floating action button... I have in my drawable folder white transparent background and I want to display it, when that button is clicked.

I tryed this:
`android:onClick="fab_menu_clicked"`
but it didn't work...

What should I do?

**Comment by EndzeitBegins** [comment]
I had the same problem. 

The solution I found is to add any action into the onPrepareMenu() method of the SimpleMenuListenerAdapter as this method is called everytime the FAB is clicked, when the menu is closed.
If it's opened and the FAB is pressed the onMenuClosed() method should be triggered

Hope this helps.
