### ISSUE TITLE
Detect when no one of items selected

### ISSUE THREAD

**Issue by bestak** [yavski/fab-speed-dial#27]
Hello, I just want to ask, if there is a way how to detect when no one of all items is clicked (or when is clicked on screen completly away from fab-speed-dial)

I want to disappear white transparent from screen...

What should I do? :)

**Comment by saibbyweb** [comment]
Did you find any solution?

**Comment by yavski** [comment]
@saibbyweb If you're still looking for an answer [here](https://github.com/yavski/fab-speed-dial/blob/master/library/src/main/java/io/github/yavski/fabspeeddial/FabSpeedDial.java#L89) it is.
