### ISSUE TITLE
fabSpeedDial.show(); don't work

### ISSUE THREAD

**Issue by MrMichaelFournier** [yavski/fab-speed-dial#31]
Hi

I implemented your lib today to replace my floatingActionButton.
I set your FabSpeedDial with visibility setted as "gone" in my xml but when I call fabSpeedDial.show();, it simply doesn't work.
I does with the original fab.

Why do you check "if (!ViewCompat.isAttachedToWindow(this))" ?

thank you for your work

**Comment by yavski** [comment]
It's just belt & braces. Would it not work for you if you made it invisible?

**Comment by MrMichaelFournier** [comment]
I tried both gone and invisible and is doesn't show
So I guess maybe the isAttachedToWindow is the problem
