### ISSUE TITLE
Hide FAB On Scroll in Coordinator Layout

### ISSUE THREAD

**Issue by rayliverified** [yavski/fab-speed-dial#59]
This is a great library! If only it could behave like the FAB in the support library and hide on scroll. 
Like this behavior demoed: 
https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2016/01/1453282702Float-FAB.gif
I tried to make the library's FAB hide on scroll by following this tutorial (https://www.sitepoint.com/animating-android-floating-action-button/) but the library does not extend FAB so it did not work. 
I am going to look into implementing this feature in the next few days. Most likely, it requires a bit of code in the library and then some code in the RecyclerView onScrollListener.

**Comment by Henriquedn** [comment]
import android.content.Context;
import android.support.design.widget.CoordinatorLayout;
import android.support.v4.view.ViewCompat;
import android.util.AttributeSet;
import android.view.View;
import android.view.animation.LinearInterpolator;

import io.github.yavski.fabspeeddial.FabSpeedDial;
import io.github.yavski.fabspeeddial.FabSpeedDialBehaviour;

/**
 * Credits for animation to 
 * https://www.sitepoint.com/animating-android-floating-action-button/
 */

public class FABScrollBehavior extends FabSpeedDialBehaviour {

	public FABScrollBehavior(Context context, AttributeSet attributeSet){
		super();
	}


	@Override
	public void onNestedScroll(CoordinatorLayout coordinatorLayout, FabSpeedDial child, View target, int dxConsumed, int dyConsumed, int dxUnconsumed, int dyUnconsumed) {
		super.onNestedScroll(coordinatorLayout, child, target, dxConsumed, dyConsumed, dxUnconsumed, dyUnconsumed);
		
		if (dyConsumed > 0) {
			CoordinatorLayout.LayoutParams layoutParams = (CoordinatorLayout.LayoutParams) child.getLayoutParams();
			int fab_bottomMargin = layoutParams.bottomMargin;
			child.animate().translationY(child.getHeight() + fab_bottomMargin).setInterpolator(new LinearInterpolator()).start();
		} else if (dyConsumed < 0) {
			child.animate().translationY(0).setInterpolator(new LinearInterpolator()).start();
		}
	}

	@Override
	public boolean onStartNestedScroll(CoordinatorLayout coordinatorLayout, FabSpeedDial child, View directTargetChild, View target, int nestedScrollAxes) {
		return nestedScrollAxes == ViewCompat.SCROLL_AXIS_VERTICAL;
	}
}

**Comment by Kolyall** [comment]
@Henriquedn thanks

**Comment by DanteAndroid** [comment]
how to use? Thx!

**Comment by rayliverified** [comment]
Thank you @Henriquedn for posting this solution! I was on vacation for the past week so I was unable to express my gratitude sooner. It works perfectly, God bless!

**Comment by rayliverified** [comment]
@DanteAndroid 
Create a file named FABScrollBehavior and copy/paste @Henriquedn's code into the class. 
Then add app:layout_behavior="yourfile.location.FABScrollBehavior" to the layout XML.
```
        <io.github.yavski.fabspeeddial.FabSpeedDial
            android:id="@+id/main_fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            app:layout_behavior="yourfile.location.FABScrollBehavior"
            app:fabGravity="bottom_end"
            app:fabMenu="@menu/menu_popup_view"
            app:fabBackgroundTint="@color/colorPrimary"
            app:miniFabBackgroundTint="@color/colorPrimary"
            app:miniFabDrawableTint="@color/white"
            app:miniFabTitleTextColor="@color/textPrimary"/>
```
Make sure the FAB is wrapped in a android.support.design.widget.CoordinatorLayout
Hope this helps!

**Comment by Henriquedn** [comment]
@searchy2 Welcome. 
Awesome library. The use of menu file resource makes it standout and easier to use.
